name: Build

on:
  push:
    branches: 
      - "**"
    tags:
      - "*"

permissions: 
  checks: write
  pull-requests: write

jobs:
  validate-version:
    name: 🧐 Validate Version
    uses: ./.github/workflows/validate-version-job.yml
    if: startsWith(github.ref, 'refs/tags/')

  build:
    name: 🏗️ Build Nuget Package
    uses: ./.github/workflows/build-job.yml
    with:
      dotnet-version: '10.0.x'
  
  publish-nuget:
    name: 📦 Publish Nuget Package
    uses: ./.github/workflows/publish-nuget-job.yml
    needs: [build, validate-version]
    if: startsWith(github.ref, 'refs/tags/')
    with:
      dotnet-version: '10.0.x'
    secrets: inherit
